### ISSUE TITLE
Extention auch für Firefox (oder tampermonkey)

### ISSUE THREAD

**Issue by SpeeterYT** [oliverjessner/blauherzfilter#2]
Hi 👋 
Wäre es möglich die extention auch für Firefox (oder tampermonkey) verfügbar zu machen? (Würde dann auch theoretisch auch auf mobile funktionieren) 
Wäre nice, da ich auf all meinen Geräten nur Firefox nutze

**Comment by oliverjessner** [comment]
Hi gestern wurden wird für den Firefox Add-on Store freigeschalten :) 

[firefox](https://addons.mozilla.org/en-US/firefox/addon/blauherzfilter/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
